### ISSUE TITLE
[Bug] Mirage error on api calls

### ISSUE THREAD

**Issue by geromegrignon** [romansndlr/react-vite-realworld-example-app#19]
## Description

The app works fine locally using `npm run dev` (with fake data).

But the deployed app throws an error in the browser's console for API calls :

```
Mirage: Your app tried to GET 'https://conduit.pro…s() config. Did you forget to define a namespace?"
```

It happens with both tags, and articles API calls on the Home page.

I can reproduce it by cloning the repo and deploying a production build.
I can reproduce it with our new temporarily new API (https://realworld-temp-api.herokuapp.com/api).

**Comment by romansndlr** [comment]
Fixed, thank you!
